### ISSUE TITLE
`bionetgen.xmlapi.model.bngmodel.compartments` attribute is absent for non-compartmentalized models rather than an empty dict

### ISSUE THREAD

**Issue by jonrkarr** [RuleWorld/PyBioNetGen#1]
I found it surprising that `bionetgen.xmlapi.model.bngmodel.compartments` is missing from non-compartmentalized models. I expected this to be an empty block rather than they're not being an attribute at all because the attributes of classes don't usually depend on the data that each instance represents.

**Comment by jonrkarr** [comment]
It looks like all blocks are handled this way.

**Comment by ASinanSaglam** [comment]
Yes, the `active_blocks` attribute is the list of blocks that are parsed. I need to think about what makes the most sense here, in a BNGL string an empty block is simply not written instead of being an empty block. Either one works in BNGL. This structure is meant to represent the model as 1-1 as possible, so it made more sense to me to not have the block at all. This is especially true since there are 2-3 valid blocks in BNGL that are very rarely used and the model would have those too, not just compartments block.

**Comment by jonrkarr** [comment]
While that's true of BNGL files, attributes of classes don't usually work this way. I point this out because others will likely be surprised by this convention, which differs from the convention of Python and most other programming languages.

**Comment by ASinanSaglam** [comment]
That's true, I'll adjust it so that the attributes exist but are not printed out during model string generation if empty. That does make sense to me as well.

**Comment by ASinanSaglam** [comment]
This will need more work down the line to ensure adding and removing items adjust active block list correctly but this should work to address this issue.
