### ISSUE TITLE
How to change initial conditions of loaded BioNetGen model?

### ISSUE THREAD

**Issue by TorkelE** [RuleWorld/PyBioNetGen#42]
I have a BioNetGen model that I have loaded from a .bngl file. I can simulate it through:
```python
import bionetgen
model = bionetgen.bngmodel('model.bngl')
result = bionetgen.run(model, suppress=True);
```
however, I want to adjust the initial conditions of the model. I can access the first species' s initial condition through:
```python
model.xml_dict['sbml']['model']['ListOfSpecies']['Species'][0]['@concentration']
```
I attempt to change it through
```python
model.xml_dict['sbml']['model']['ListOfSpecies']['Species'][0]['@concentration'] = 10
```
If I then print the value it appears to have changed. However, If I then simulate it again, the simulation doesn't change
(manually make a change in the .bngl file does seem to cause a change though)

Is there some way to do this that I am missing?

**Comment by cjarmstrong97** [comment]
Hi,

PyBioNetGen only uses an .xml file to create and populate the `bngmodel` object, but doesn't reference it again after that.

Instead, use
```
model.species[0].count = 10
```
which will access the initial condition stored in the Python object.
This should change the result of your simulation the next time you run
```
result = bionetgen.run(model, suppress=True)
```

Please let me know if this works for you.

**Comment by TorkelE** [comment]
Thanks
yes, that worked, ish.

Using this method I can only access a limited number of species, those declared in 
```
begin seed species 
BCR(Y188_Y199~0,Y196_Y207~0)                 p1   
Lyn(unique,SH3,SH2,Y397~0,Y508~0)             p1   
Fyn(unique,SH3,SH2,Y420~0,Y531~0)              p1  
PAG(PRS1,PRS2,Y317~0,Y163_Y181~0,Y387_Y417~0)  p1   
Csk(SH2)                                       p1 
Syk(tSH2,Y525_Y526~0)                          p1 
end seed species 
```
but the system ends up with a lot more species, and I want to access these as well.

**Comment by TorkelE** [comment]
It does not.

**Comment by cjarmstrong97** [comment]
If you include a `writeXML()` action in your bngl file and run it using the `run` subcommand, you should get an .xml file of your model. Then, use that file instead of the .bngl when you create your model object in Python, i.e.
```
model = bionetgen.bngmodel('model.xml')
```
 
  
There are a few drawbacks in doing this, however. Unfortunately, `toXML()` doesn't support actions, so you will have to use
```
model.add_action(action_type, action_args)
```
to add your desired actions back into the model object before using `bionetgen.run()`. For reference, `action_type` should be the name of the action as a string, while `action_args` is a dictionary of argument names and values, e.g.
```
model.add_action('simulate_ode', {'t_end':10, 'n_steps':20})
```  
  
You can try a few different placements of `writeXML()` relative to your other actions, but if all else fails, you can place `writeXML()` at the very end of your .bngl file. This will guarantee that the `model` object contains all the species generated by the system (user-defined and otherwise), but you will probably have to manually reset values in your model using the method from earlier, depending on what other actions are run before `writeXML()`.  
  
I know this solution is a bit awkward, but I hope it lets you access the values you want. If a better solution comes to mind, I'll provide it here, and I'd be happy to try to answer any further questions or concerns you have.

**Comment by TorkelE** [comment]
Thank you,
I was able to create and open the xml file, and simulate it by adding the action. However, the model only seem to contain a limited number of species. E.g. when I try
```python
model.xml_dict['sbml']['model']['ListOfSpecies']['Species']
```
It only has 6 different ones. Am I looking in the wrong part of the model, or am I doing something else that is wrong.

**Comment by cjarmstrong97** [comment]
Would you mind sharing the actions you have in your .bngl file? My first guess is that `writeXML()` might need to be moved before or after some other actions.
  
It would probably be better to look through your species by trying
```
model.species
```
but I'm 99% positive that it should match the values from `xml_dict` anyway.

**Comment by TorkelE** [comment]
Ahh, yeah, `model.species` seems a much better idea. I am attaching the .bngl file I used to generate the .xml file (I changed the extension to .txt so that GitHub would permit it to be uploaded).
[BCR.txt](https://github.com/RuleWorld/PyBioNetGen/files/8231164/BCR.txt)

**Comment by TorkelE** [comment]
Hello,
thank you, yes that worked. I use a .bngl file with this:
``` 
simulate({method=>"ode",t_end=>10,n_steps=>1000})
writeXML()
``` 
at the end. I can then load the .XML file using
```python
model_BCR_xml = bionetgen.bngmodel('../BCR.xml')
```
it also got all the species that I can modify.

However, there seems to happen something funny. If I load the initial .bngl file and simulate it (but without the `writeXML()` action):
```python
# Load model.
model_BCR = bionetgen.bngmodel('BCR.bngl')
result_BCR_ODE = bionetgen.run(model_BCR, suppress=True);
plot_result(result_BCR_ODE)
```
(where `plot_result` is
```python
# Function for plotting simulation output.
def plot_result(result):
    r = result[0]

    for name in r.dtype.names:
        if name != "time":
            plt.plot(r['time'], r[name], label = name)
    plt.xlabel("time")
    plt.ylabel("species (counts)")
    _ = plt.legend(frameon = False)
    return plt
```
)

I get an output:
![image](https://user-images.githubusercontent.com/18099310/158024060-15aa0fbb-f9a3-4f38-a93c-6baf9ba86e8b.png)


However, if I try to use the .XML file (without doing anything to initial conditions):
```python
model_BCR_xml = bionetgen.bngmodel('BCR.xml')
model_BCR_xml.add_action('simulate', {'method':'"ode"', 't_end':10, 'n_steps':1000})
result_BCR_ODE_xml = bionetgen.run(model_BCR_xml, suppress=True);
plot_result(result_BCR_ODE_xml)
```
I get an output:
![image](https://user-images.githubusercontent.com/18099310/158024111-1639cdab-b916-4030-be05-bf9e9b150adc.png)


The two actions should be the same though, but is there something by going through the .XML format that changes the simulation?

**Comment by cjarmstrong97** [comment]
I believe the `writeXML()` action writes the system to .xml format in whatever state it is in when the action is run. So, since `writeXML()` comes after your `simulate()` action, all the values in your .xml (and your results from using the .xml) reflect the system post-simulation. Since you need the `simulate()` action to create all the other species, I don't think this method will work that well unless you're willing to manually reset all the initial conditions in your `model` object.

If you'd rather not reset all those values using the .xml file and you're only interested in a few of the extra species generated by `simulate()`, I would suggest adding those species directly to the `species`/`seed species` block in your BNGL file. Then you can avoid using the .xml file, since those species will then be accessible from `model.species`.
